lib/memo_web/router.ex
defmodule MemoWeb.Router do
  use MemoWeb, :router

  import MemoWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MemoWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MemoWeb do
    pipe_through :browser

    live "/", HomeLive
  end

  # Other scopes may use custom stacks.
  # scope "/api", MemoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MemoWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", MemoWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", MemoWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    get "/users/profile", UserProfileController, :index
  end

  scope "/", MemoWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/memo_web/views/layout_view.ex
defmodule MemoWeb.LayoutView do
  use MemoWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/memo_web/templates/layout/app.html.heex
<header x-data="{open: false, userMenuOpen: false}" class="max-h-12 m-0 pl-2 pr-2">
  <section class="flex flex-row md:flex-row items-center m-0 p-0 items-start justify-between">
    <a href="/" class="flex-grow">
      <h2 id="logo" class="flex-initial text-2xl w-20">
        M<span class="text-base">e</span><span class="italic">M</span><span class="text-base italic">o</span>
      </h2>
    </a>
    
    <%= if @current_user do %>
     <div class="ml-10 mr-5">
        <div class="max-w-xs flex text-sm rounded-full 
                      text-white focus:outline-none focus:shadow-solid"
          x-on:click="userMenuOpen = true"
          x-on:click.away="userMenuOpen = false">
          <p class="text-sm leading-5 font-medium group-hover:text-gray-900">
            <%= @current_user.email %>
          </p>
        </div>
        <div class="
            origin-top-right
            absolute 
            right-0 
            mt-2 
            w-48 
            rounded-md shadow-lg"
            style='z-index:5;'
              x-show.transition="userMenuOpen"
              x-cloak>
          <div class="py-1 rounded-md bg-white shadow-xs" role="menu">
            <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "block px-4 py-2 text-sm leading-5 hover:bg-gray-100" %>
            <%= link "Profile", to: Routes.user_profile_path(@conn, :index), class: "block px-4 py-2 text-sm leading-5 hover:bg-gray-100" %>
            <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "block px-4 py-2 text-sm leading-5 hover:bg-gray-100"%>  
          </div>
        </div>
    </div>
    <% else %>
      <div class="ml-5"><%= link "Sign up", to: Routes.user_registration_path(@conn, :new) %></div>
      <div class="ml-5"><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></div>
    <% end %>
  </section>
</header>
<main>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/memo_web/templates/layout/live.html.heex
<header x-data="{open: false, userMenuOpen: false}" class="max-h-12 m-0">
  <section class="flex flex-row md:flex-row items-center m-0 p-0 items-start">
    <a href="/">
      <h2 id="logo" class="flex-initial text-2xl w-20">
        M<span class="text-base">e</span><span class="italic">M</span><span class="text-base italic">o</span>
      </h2>
    </a>
    
    <form phx-change="search" phx-submit="search" id="header-search" class="flex-grow text-xs ml-10">
      <input type="text" placeholder="Search creator, user, title..." phx-debounce="2000" name="term" class="text-xs w-full" value={@term}/>
    </form>
    <%= if @current_user do %>
      <button x-on:click="open = true" class="w-12 ring-4 ring-yellow-500 text-white h-6">+</button>
    <% end %>
    
    <%= if @current_user do %>
     <div class="ml-10 mr-5">
        <div class="max-w-xs flex text-sm rounded-full 
                      text-white focus:outline-none focus:shadow-solid"
          x-on:click="userMenuOpen = true"
          x-on:click.away="userMenuOpen = false">
          <p class="text-sm leading-5 font-medium group-hover:text-gray-900 cursor-pointer">
            <%= @current_user.username %>
          </p>
        </div>
        <div class="
            origin-top-right
            absolute 
            right-0 
            mt-2 
            w-48 
            rounded-md shadow-lg"
            style='z-index:5;'
              x-show.transition="userMenuOpen"
              x-cloak>
          <div class="py-1 rounded-md bg-white shadow-xs" role="menu">
            <%= link "Settings", to: Routes.user_settings_path(@socket, :edit), class: "block px-4 py-2 text-sm leading-5 hover:bg-gray-100" %>
            <%= link "Profile", to: Routes.user_profile_path(@socket, :index), class: "block px-4 py-2 text-sm leading-5 hover:bg-gray-100" %>
            <%= link "Log out", to: Routes.user_session_path(@socket, :delete), method: :delete, class: "block px-4 py-2 text-sm leading-5 hover:bg-gray-100"%>  
          </div>
        </div>
    </div>
    <% else %>
      <div class="ml-5"><%= link "Sign up", to: Routes.user_registration_path(@socket, :new) %></div>
      <div class="ml-5"><%= link "Log in", to: Routes.user_session_path(@socket, :new) %></div>
    <% end %>
  </section>
  
  <.live_component module={MemoWeb.ParseComponent} id="parse_component"/>
</header>
<main class="container m-0 p-0">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/memo_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Memo" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer type="text/javascript" src="https://unpkg.com/alpinejs@3.5.0/dist/cdn.min.js"></script>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>